### ISSUE TITLE
[Feature Request] Manually pause the Index Operator

### ISSUE THREAD

**Issue by JesusTheHun** [brantburnett/couchbase-index-operator#16]
Following [this issue](https://github.com/brantburnett/couchbase-index-operator/issues/14), it would be nice to be able to manually pause the Index Operator when we perform maintenance operations.

```yaml
spec:
  pause: true
  cluster: 
    manual:
      connectionString: couchbase://cb-example
```
