### ISSUE TITLE
No event after applying resource

### ISSUE THREAD

**Issue by JesusTheHun** [brantburnett/couchbase-index-operator#6]
Sorry I'm using issues to get some help, there is no "discussion" tab enabled.

So I wanted to try things out and after installing the CRD, I apply the following : 

```yaml
apiVersion: couchbase.btburnett.com/v1beta1
kind: CouchbaseIndexSet
metadata:
  name: couchbase-indexset-acme
spec:
  cluster:
    clusterRef:
      name: couchbase-db-couchbase-cluster
      secretName: couchbase-secret-admin
  bucketName: acme
  indices:
    - name: object_type
      indexKey:
        - _class
```

Then I check with `kubectl describe couchbaseindexset couchbase-indexset-acme` and it shows no event. And nothing is happening on the couchbase side. The controller container says it is listening and nothing more.
Both the couchbase cluster and the indexset are in the same namespace.

How can I troubleshoot that ?
